"""Build the static portfolio pages. Run `python3 build_site.py` in this folder."""
from pathlib import Path
from html import escape
import re

ROOT = Path(__file__).resolve().parent
NAME = "Caua Kevyn Martins Brasil"
EMAIL = "cm2080@scarletmail.rutgers.edu"
LINKEDIN = "https://www.linkedin.com/in/kevin-brasil-6b93032a8/"

NAV = [
    ("Overview", "index.html"),
    ("About", "about.html"),
    ("Projects", "projects.html"),
    ("Experience", "experience.html"),
    ("Highlights", "highlights.html"),
    ("Interests", "interests.html"),
    ("Resume", "resume.html"),
    ("Contact", "contact.html"),
]


def page(title: str, description: str, current: str, content: str) -> str:
    # Give longer pages useful section navigation with stable, unique anchors.
    section_links = []
    def section_heading(match):
        label = re.sub(r"<[^>]+>", " ", match.group(1)).strip()
        anchor = "section-" + re.sub(r"[^a-z0-9]+", "-", label.lower()).strip("-")
        section_links.append((anchor, label))
        return f'<h2 id="{anchor}">{match.group(1)}</h2>'
    content = re.sub(r"<h2>(.*?)</h2>", section_heading, content)
    if current not in ("index.html", "resume.html", "contact.html") and len(section_links) >= 3:
        jumps = ''.join(f'<a href="#{anchor}">{label}</a>' for anchor, label in section_links)
        content = content.replace('</header>', '<nav class="section-nav" aria-label="On this page"><span>On this page</span>' + jumps + '</nav></header>', 1)
    links = "\n".join(
        f'<li><a href="{href}"' + (' aria-current="page"' if current == href else '') + f'>{label}</a></li>'
        for label, href in NAV
    )
    return f'''<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="{escape(description, quote=True)}">
  <meta name="theme-color" content="#cc0033">
  <title>{escape(title)} | {NAME}</title>
  <link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' fill='%23cc0033'/%3E%3Ctext x='32' y='42' text-anchor='middle' font-family='Arial,sans-serif' font-weight='bold' font-size='23' fill='white'%3EKB%3C/text%3E%3C/svg%3E">
  <link rel="stylesheet" href="site.css?v=7">
</head>
<body>
  <a class="skip-link" href="#main">Skip to content</a>
  <header class="site-header">
    <a class="brand" href="index.html" aria-label="{NAME}, home"><span class="brand-mark" aria-hidden="true">KB<span>↗</span></span><span class="brand-name">Caua Kevyn<br>Martins Brasil</span></a>
    <p class="nav-caption">Finance portfolio</p>
    <nav aria-label="Primary"><ul class="nav-list">{links}</ul></nav>
    <div class="sidebar-school"><span class="school-rule"></span><strong>Rutgers<br>Business School</strong><span>BS in Finance · 2028</span></div>
    <a class="sidebar-contact" href="contact.html">Start a conversation <span>↗</span></a>
  </header>
  <div class="site-content"><div class="topline"><span>FINANCE &amp; BUSINESS</span><span>Based in New Jersey <span class="status-dot" aria-hidden="true"></span></span></div>
  <main id="main">{content}</main>
  <footer class="site-footer"><div class="wrap footer-top"><div><strong>{NAME}</strong><p>Rutgers Business School · Finance · Class of 2028</p></div><nav class="footer-links" aria-label="Footer"><a href="contact.html">Contact</a><a href="{LINKEDIN}" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="#main">Back to top ↑</a></nav><span class="copyright">© 2026</span></div></footer></div>
</body>
</html>
'''


def project_row(number: str, type_: str, title: str, blurb: str, url: str, style: str, symbol: str, foot: str, small: bool = False) -> str:
    icons = {"01": "<path d='M8 32V14h12v18M20 32V8h12v24M32 32V20h8v12M5 36h38'/>", "02": "<rect x='8' y='7' width='32' height='34' rx='3'/><path d='M15 16h18M15 24h6m6 0h6M15 32h6m6 0h6'/>", "03": "<path d='M8 15h30l-7-7M38 33H8l7 7'/><circle cx='24' cy='24' r='7'/>"}
    return f'''<article class="project-card"><div class="project-visual {style}"><svg viewBox="0 0 48 48" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">{icons[number]}</svg><span>{foot}</span></div>
      <div class="project-copy"><span class="eyebrow">{type_}</span><h3><a href="{url}">{title}</a></h3><p>{blurb}</p><a class="text-link" href="{url}">View details <span aria-hidden="true">→</span></a></div></article>'''



projects = [
    project_row("01", "Winning team · consulting", "Bergecco-Parc Consulting",
        "Collaborated on the winning Team Two proposal, connecting tourism marketing and revenue analysis with event planning for the Bergen County Historical Society.",
        "project-bergecco.html", "", "B—P", "Budgeting &amp; strategy / 2023", True),
    project_row("02", "Operations · analysis", "Cash Reconciliation &amp; Operations",
        "Reconcile $1,000–$3,000 in daily cash and deposits and analyze delivery commissions, payroll, pricing, and marketing spend at Master Pizza.",
        "project-operations.html", "rose", "01—03", "Operations / 2025–26", True),
    project_row("03", "Finance · client discovery", "Small-Business Financing",
        "Qualified small-business prospects, identified funding needs, and explained $25,000–$100,000 financing options and repayment terms.",
        "project-funding.html", "navy", "$25–100k", "Finance / 2026", True),
]


PAGES = {
"index.html": page("Overview", "Finance, business experience, and campus involvement from Caua Kevyn Martins Brasil.", "index.html", f'''
  <div class="wrap"><section class="profile-hero" aria-labelledby="hero-title">
    <div class="profile-scarlet"><span class="profile-label">FINANCE UNDERGRADUATE</span><div class="profile-word">Rutgers<br>Business<br>School</div><p class="profile-focus">Corporate finance<br>Business analysis<br>Working capital</p><div class="profile-school">Newark, New Jersey<span>BS in Finance · May 2028</span></div></div>
    <div class="profile-intro"><span class="eyebrow">Finance · Operations · Research</span><h1 id="hero-title">Caua Kevyn<br>Martins Brasil</h1><p class="lead">Finance student with hands-on business experience.</p><p class="intro-detail">I reconcile cash and deposits, analyze operating costs, and draw on experience explaining financing options to small-business owners. At Rutgers Business School, I’m building the financial knowledge to connect that practical work with corporate finance and business analysis.</p><div class="button-row"><a class="button" href="projects.html">Explore my work <span aria-hidden="true">→</span></a><a class="button secondary" href="resume.html">View resume</a></div></div>
  </section>
  <div class="evidence-strip evidence-strip-three" aria-label="Experience at a glance"><div><strong>$1K–$3K</strong><span>Daily cash &amp; deposits reconciled</span></div><div><strong>100+</strong><span>Daily outreach contacts at High Rise</span></div><div><strong>16+</strong><span>Active legal matters researched</span></div></div>
  <section class="section"><div class="section-head"><div><span class="eyebrow">Academic project &amp; professional practice</span><h2>Selected projects &amp; experience</h2></div><a class="text-link" href="projects.html">All work →</a></div><div class="project-list">{''.join(projects)}</div></section>
  <section class="highlight-section"><div class="section-head"><div><span class="eyebrow">Beyond the job titles</span><h2>Education &amp; leadership</h2></div><a class="text-link" href="highlights.html">Explore highlights →</a></div>
    <div class="milestone-grid"><article class="milestone academic"><span class="eyebrow">Bergen Community College</span><strong class="big-stat">3.89<span>GPA</span></strong><h3>Business Administration</h3><p>AS in Business Administration · May 2026<br>Dean’s List recognition</p></article><article class="milestone"><span class="tile-icon" aria-hidden="true">↗</span><span class="eyebrow">Leadership</span><h3>Legal Studies Club President</h3><p>Led club operations, organized programming, and engaged members around law, business, and professional development.</p><a class="text-link" href="highlights.html#leadership">Leadership &amp; involvement →</a></article><article class="milestone"><span class="tile-icon" aria-hidden="true">✳</span><span class="eyebrow">Recognition</span><h3>Scholarship recognition</h3><p>Moses Family Endowed Scholarship and LEO Foundation Endowed Scholarship.</p><a class="text-link" href="highlights.html#recognition">Academic highlights →</a></article></div>
  </section>
  <section class="toolkit-section"><div><span class="eyebrow">Technical toolkit</span><h2>Tools &amp; interests</h2><p>Excel (PivotTables and formulas), Google Sheets, QuickBooks, Python, and PowerPoint.</p></div><div><p>Alongside finance, I’m interested in fashion, design, consumer psychology, and gaming. Those interests give me different ways to think about businesses and the people they serve.</p><a class="text-link" href="interests.html">Explore my interests →</a></div></section><section class="section journey-section"><div><span class="eyebrow">The journey so far</span><h2>Career development</h2><p class="body-copy">I’ve checked daily financial records, explained funding options, and synthesized legal research—building a foundation in analysis and communication.</p><a class="text-link" href="about.html">Get to know me →</a></div><div class="journey-list"><a href="highlights.html#leadership"><span>2026</span><div><h3>A new chapter at Rutgers</h3><p>Pursuing a finance degree and joining the Rutgers ALPFA community.</p></div><span aria-hidden="true">↗</span></a><a href="experience.html"><span>2025–26</span><div><h3>Business from the inside</h3><p>Operations at Master Pizza; finance at High Rise Capital.</p></div><span aria-hidden="true">↗</span></a><a href="project-bergecco.html"><span>2023</span><div><h3>A winning team proposal</h3><p>Bergecco-Parc Consulting: budgeting and tourism strategy for the Bergen County Historical Society.</p></div><span aria-hidden="true">↗</span></a></div></section>
  <section class="connect-banner"><div><span class="eyebrow">Let’s connect</span><h2>Have an opportunity in mind?</h2><p>I’d be glad to talk about finance internships, analytical projects, and business operations.</p></div><a class="button" href="contact.html">Get in touch ↗</a></section></div>'''),

"highlights.html": page("Highlights", "Academic recognition, leadership, and campus involvement.", "highlights.html", '''<div class="wrap"><header class="page-intro"><span class="eyebrow">Beyond the resume</span><h1>Achievements &amp; involvement</h1><p class="lead">The communities, achievements, and experiences that are shaping my path.</p></header>
<section id="recognition" class="highlight-section"><div class="section-head"><div><span class="eyebrow">Education &amp; awards</span><h2>Academic recognition</h2></div></div><div class="milestone-grid"><article class="milestone academic"><span class="eyebrow">Bergen Community College</span><strong class="big-stat">3.89<span>GPA</span></strong><h3>Business Administration</h3><p>Associate in Science · May 2026<br>Dean’s List recognition</p></article><article class="milestone"><span class="tile-icon" aria-hidden="true">✳</span><span class="eyebrow">Scholarship</span><h3>Moses Family<br>Endowed Scholarship</h3><p>Received the Moses Family Endowed Scholarship while studying at Bergen Community College.</p></article><article class="milestone"><span class="tile-icon" aria-hidden="true">✳</span><span class="eyebrow">Scholarship</span><h3>LEO Foundation<br>Endowed Scholarship</h3><p>Received the LEO Foundation Endowed Scholarship during my studies at Bergen Community College.</p></article></div></section>
<section class="connect-banner"><div><span class="eyebrow">Team achievement · December 2023</span><h2>Bergecco-Parc Consulting: winning team</h2><p>Collaborated with the winning Team Two on a tourism and fundraising proposal for the Bergen County Historical Society. We connected ticket pricing and event costs to a museum fundraising goal. Explore the presentation and instructor’s recap on the project page.</p></div><a class="button" href="project-bergecco.html">Explore the project →</a></section>
<section id="leadership" class="section"><div class="section-head"><div><span class="eyebrow">Leadership &amp; involvement</span><h2>Campus leadership</h2></div></div><div class="involvement-grid"><article class="involvement-card"><span class="eyebrow">President · September 2024–May 2025</span><h3>Legal Studies Club</h3><p class="organization">Bergen Community College</p><p>Organized club programming and engaged members in law, business, and professional development.</p></article><article class="involvement-card"><span class="eyebrow">Member · 2026–present</span><h3>ALPFA</h3><p class="organization">Rutgers University</p><p>Association of Latino Professionals For America · Rutgers University chapter.</p></article><article class="involvement-card wide"><span class="eyebrow">Additional involvement</span><h3>Bergen campus involvement</h3><ul class="chip-list"><li>Student Government Association · Judicial Member</li><li>Latin American Student Association · Member</li><li>Motion: Student Achievement Club · Member</li></ul></article></div></section>
<section class="connect-banner"><div><span class="eyebrow">Put it in context</span><h2>See the experience behind the highlights</h2><p>Explore my work in operations, finance, and research.</p></div><a class="button" href="experience.html">My experience →</a></section></div>'''),

"about.html": page("About", "Learn about Caua Kevyn Martins Brasil's education, leadership, and interest in finance.", "about.html", f'''
  <div class="wrap"><header class="page-intro"><span class="eyebrow">The person behind the work</span><h1>About me</h1>
    <p class="lead">I’m studying finance at Rutgers Business School in Newark. My experience in operations, small-business financing, and legal research has made me interested in both the numbers behind a business and the people making its decisions.</p></header>
    <section class="split-section"><div><span class="eyebrow">Perspective</span><h2>My background</h2></div><div class="body-copy">
      <p>At Master Pizza, I reconcile cash and deposits and examine delivery commissions, payroll, pricing, and marketing spend. Working through these details helps me understand how everyday operating decisions affect a business’s performance.</p>
      <p>At High Rise Capital, I identified small-business owners’ funding needs and explained financing options in plain language. In my legal internship, I researched active matters and organized findings for attorneys. Across these roles, I’ve practiced checking details, synthesizing information, and explaining it clearly.</p>
    </div></section>
    <section class="split-section"><div><span class="eyebrow">Academic foundation</span><h2>Education</h2></div><div class="body-copy">
      <p>I’m pursuing a Bachelor of Science in Finance at Rutgers Business School, with an expected graduation in May 2028. I earned an Associate in Science in Business Administration from Bergen Community College in May 2026, graduating with a 3.89 GPA and Dean’s List recognition.</p>
      <p>Through accounting, statistics, economics, Python, and spreadsheet work, I’m learning to connect classroom concepts to business questions. I received the Moses Family Endowed Scholarship and the LEO Foundation Endowed Scholarship at Bergen.</p>
    </div></section>
    <section class="split-section"><div><span class="eyebrow">Community</span><h2>Leadership &amp; community</h2></div><div class="body-copy">
      <p>As president of Bergen’s Legal Studies Club, I organized programming and member engagement around law, business, and professional development. At Rutgers, I’m a member of the Association of Latino Professionals For America (ALPFA).</p>
      <p>At Bergen, I served as a judicial member of the Student Government Association and participated in the Latin American Student Association and Motion: Student Achievement Club. I speak Portuguese natively and am proficient in Spanish—skills that help me connect with people across backgrounds.</p>
    </div></section>
    <section class="split-section"><div><span class="eyebrow">Outside the classroom</span><h2>Personal interests</h2></div><div class="body-copy"><p>I’m interested in fashion and resale, creative design, and the psychology behind consumer decisions. I also enjoy gaming, including Overwatch and Hearts of Iron IV.</p><p>These sit alongside my interest in learning about financial markets and understanding how businesses grow.</p><a class="text-link" href="interests.html">More about my interests →</a></div></section><section class="section"><div class="section-head"><div><span class="eyebrow">How I work</span><h2>What I bring to a team</h2></div></div>
      <div class="card-grid"><div class="info-card"><span class="eyebrow">01</span><h3>Attention to detail</h3><p>Verify daily cash totals and organize research into clear, usable records.</p></div><div class="info-card"><span class="eyebrow">02</span><h3>Clear communication</h3><p>Listen to business needs and explain financing terms in plain language.</p></div><div class="info-card"><span class="eyebrow">03</span><h3>Operational perspective</h3><p>Examine operating costs and connect the numbers to day-to-day business decisions.</p></div></div>
    </section></div>'''),

"projects.html": page("Projects", "Consulting, operational analysis, and finance work from Caua Kevyn Martins Brasil.", "projects.html", f'''
  <div class="wrap"><header class="page-intro compact"><span class="eyebrow">Selected work</span><h1>Projects &amp; applied experience</h1>
    <p class="lead">Explore a winning academic consulting proposal and two examples of my professional responsibilities. Each entry connects the work to budgeting, operating performance, or business financing.</p></header>
    <section class="project-feature"><div><span class="eyebrow">Academic consulting · Winning team</span><h2>Bergecco-Parc Consulting</h2><p>Our team developed a tourism and fundraising proposal for the Bergen County Historical Society. Explore how we combined event concepts, ticket assumptions, and projected costs in the presentation.</p><ul class="chip-list"><li>Revenue planning</li><li>Event budgeting</li><li>Bilingual marketing</li></ul><a class="button" href="project-bergecco.html">Explore the consulting project →</a></div><div class="project-fact"><span>Team projection</span><strong>$25,042</strong><p>Net proceeds under the original fundraising assumptions.</p><small>Academic proposal · December 2023</small></div></section>
    <section class="section"><div class="section-head"><div><span class="eyebrow">Professional practice</span><h2>Experience in business settings</h2></div></div><div class="project-list project-list-two">{''.join(projects[1:])}</div></section>
    <section class="statement"><h2>How the work relates to finance</h2><div class="body-copy"><p>In the consulting project, our team modeled revenue and expenses against a fundraising target. At Master Pizza, I reconcile cash and examine operating costs. At High Rise Capital, I qualified prospects and explained business financing options.</p><a class="text-link" href="experience.html">View professional experience <span aria-hidden="true">↗</span></a></div></section>
  </div>'''),

"experience.html": page("Experience", "Professional experience in operations, finance, and legal research.", "experience.html", f'''
  <div class="wrap"><header class="page-intro compact"><span class="eyebrow">Operations · Finance · Legal research</span><h1>Professional experience</h1>
    <p class="lead">I reconcile financial records, analyze operating costs, and build on experience qualifying business prospects and researching legal matters. These responsibilities shape how I approach finance: check the details, understand the business, and communicate clearly.</p></header>
    <section class="timeline" aria-label="Professional experience">
      <article class="timeline-entry"><span class="timeline-date">June 2025 — present<br>Carlstadt, NJ</span><div><h2>Master Pizza</h2><p class="role-name">Operations intern &amp; team lead</p>
        <ul><li>Reconcile roughly $1,000–$3,000 in daily cash and deposits, checking end-of-day totals and maintaining deposit records.</li><li>Analyze delivery commissions, payroll, marketing budgets, and pricing to identify their impact on operating performance.</li><li>Help coordinate shifts and train new staff on POS systems and store procedures.</li></ul>
        <ul class="chip-list"><li>Cash reconciliation</li><li>Margin awareness</li><li>Operating costs</li></ul></div></article>
      <article class="timeline-entry"><span class="timeline-date">May — June 2026<br>Manhattan, NY</span><div><h2>High Rise Capital</h2><p class="role-name">Finance intern</p>
        <ul><li>Conducted 100+ daily outbound contacts to prospect and qualify small-business owners for working-capital solutions.</li><li>Identified business funding needs, explained how working capital could cover payroll or advertising, and connected financing options to those priorities.</li><li>Explained $25,000–$100,000 financing structures, clarified repayment terms, and discussed how each option fit the business’s needs.</li><li>Maintained prospect records and helped advance qualified leads through application and funding stages.</li></ul>
        <ul class="chip-list"><li>Client discovery</li><li>Working capital</li><li>Financial communication</li></ul></div></article>
      <article class="timeline-entry"><span class="timeline-date">October 2023 — October 2024<br>Lyndhurst, NJ</span><div><h2>Gencarelli’s &amp; Ramasa Law Firm</h2><p class="role-name">Legal intern</p>
        <ul><li>Researched 16+ active matters and synthesized findings into structured briefs and case-preparation materials for attorneys, with attention to accuracy and confidentiality.</li><li>Helped draft interrogatories, oral-argument materials, and litigation documents for attorneys handling medical malpractice matters.</li><li>Gathered supporting records in coordination with attorneys and medical professionals and maintained confidential case files.</li></ul>
        <ul class="chip-list"><li>Research</li><li>Written synthesis</li><li>Confidentiality</li></ul></div></article>
    </section>
    <section class="section"><div class="section-head"><div><span class="eyebrow">What connects these roles</span><h2>Analysis in context</h2></div></div>
      <div class="card-grid"><div class="info-card"><span class="eyebrow">Operations</span><h3>Cash &amp; operating costs</h3><p>Verify cash and deposit totals, then examine how payroll, delivery commissions, and pricing affect operating performance.</p></div><div class="info-card"><span class="eyebrow">Finance</span><h3>Working-capital needs</h3><p>Identify why a business needs capital and explain funding amounts, repayment terms, and product fit.</p></div><div class="info-card"><span class="eyebrow">Research</span><h3>Research &amp; synthesis</h3><p>Synthesize research into structured briefs that help attorneys locate relevant findings.</p></div></div>
    </section></div>'''),

"resume.html": page("Resume", "Resume overview for Caua Kevyn Martins Brasil, finance student at Rutgers Business School.", "resume.html", f'''
  <div class="wrap"><header class="page-intro compact"><span class="eyebrow">Caua Kevyn Martins Brasil</span><h1>Resume</h1>
    <p class="lead">Finance student with experience in cash reconciliation, operating costs, small-business funding, and legal research.</p><p class="resume-contact"><a href="mailto:{EMAIL}">{EMAIL}</a> · <a href="{LINKEDIN}" target="_blank" rel="noopener noreferrer">LinkedIn</a> · New Jersey</p>
    <div class="button-row" style="margin-top:27px"><button class="button" type="button" onclick="window.print()">Print / Save PDF</button><a class="text-link" href="{LINKEDIN}" target="_blank" rel="noopener noreferrer">LinkedIn profile <span aria-hidden="true">↗</span></a></div>
  </header><section class="resume-block"><h2>Education</h2><div>
    <div class="resume-item"><h3>Rutgers Business School</h3><span class="date">Expected May 2028</span><p>Bachelor of Science in Finance · Newark, New Jersey</p></div>
    <div class="resume-item"><h3>Bergen Community College</h3><span class="date">May 2026</span><p>Associate in Science, Business Administration · 3.89 GPA · Dean’s List</p><p>Moses Family Endowed Scholarship · LEO Foundation Endowed Scholarship</p><p><strong>Coursework:</strong> Financial Accounting, Managerial Accounting, Statistics, Microeconomics, Macroeconomics, Python, and Microsoft Office.</p></div>
  </div></section><section class="resume-block"><h2>Experience</h2><div>
    <div class="resume-item"><h3>Master Pizza</h3><span class="date">June 2025 — present</span><p>Operations Intern &amp; Team Lead</p><ul class="resume-bullets"><li>Reconcile $1,000–$3,000 in daily cash and deposits and maintain accurate deposit records.</li><li>Analyze delivery commissions, payroll, marketing budgets, and pricing.</li><li>Help coordinate shifts and train new staff on POS systems and store procedures.</li></ul></div>
    <div class="resume-item"><h3>High Rise Capital</h3><span class="date">May — June 2026</span><p>Finance Intern</p><ul class="resume-bullets"><li>Conducted 100+ daily outbound contacts to prospect and qualify small-business owners.</li><li>Identified payroll and advertising funding needs and explained $25,000–$100,000 financing options, repayment terms, and product fit.</li></ul></div>
    <div class="resume-item"><h3>Gencarelli’s &amp; Ramasa Law Firm</h3><span class="date">October 2023 — October 2024</span><p>Legal Intern</p><ul class="resume-bullets"><li>Researched 16+ active matters and synthesized findings into structured briefs and case-preparation materials for attorneys.</li><li>Helped draft interrogatories, oral-argument materials, and litigation documents for attorneys handling medical malpractice matters.</li></ul></div>
  </div></section><section class="resume-block"><h2>Projects</h2><div><div class="resume-item"><h3>Bergecco-Parc Consulting</h3><span class="date">Fall 2023</span><p>Collaborated with the winning Team Two to analyze revenue streams, identify marketing channels, and develop event concepts for the Bergen County Historical Society. <a href="project-bergecco.html">Read the case study ↗</a></p></div></div></section>
  <section class="resume-block"><h2>Leadership</h2><div>
    <div class="resume-item"><h3>Legal Studies Club</h3><span class="date">September 2024 — May 2025</span><p>President · Bergen Community College</p></div>
    <div class="resume-item"><h3>ALPFA</h3><span class="date">2026 — present</span><p>Member · Rutgers University</p></div>
    <div class="resume-item"><h3>Additional campus involvement</h3><p>Student Government Association (Judicial Member) · Latin American Student Association (Member) · Motion: Student Achievement Club (Member)</p></div>
  </div></section><section class="resume-block"><h2>Skills</h2><div>
    <div class="resume-item"><h3>Tools &amp; methods</h3><p>Excel (PivotTables and formulas), QuickBooks, Google Sheets, Python, PowerPoint; financial accounting and business analysis.</p></div><div class="resume-item"><h3>Creative skills</h3><p>Canva, video editing, and content production.</p></div>
    <div class="resume-item"><h3>Languages</h3><p>Portuguese (native) · Spanish (proficient) · English</p></div>
  </div></section></div>'''),

"interests.html": page("Interests", "Finance, entrepreneurship, fashion, design, consumer psychology, and gaming interests.", "interests.html", '''<div class="wrap"><header class="page-intro"><span class="eyebrow">Professional interests &amp; life outside work</span><h1>Interests</h1><p class="lead">Finance is my academic focus. I’m also interested in what people buy, how brands communicate, and the creative work behind a business.</p></header>
<section class="interest-group"><div class="section-head"><div><span class="eyebrow">Finance &amp; business</span><h2>What I’m learning about</h2></div></div><div class="card-grid"><article class="info-card"><h3>Corporate finance</h3><p>I want to deepen my understanding of budgeting, forecasting, and performance analysis. My exposure to operating costs gives me a practical starting point for understanding how businesses plan and evaluate results.</p></article><article class="info-card"><h3>Markets &amp; investing</h3><p>I use the Investopedia Stock Simulator to explore stocks and practice tracking a portfolio with virtual funds.</p></article><article class="info-card"><h3>Small-business finance</h3><p>I’m interested in how businesses manage cash needs and evaluate financing options. My finance internship introduced me to funding discussions and the importance of clear repayment terms.</p></article></div></section>
<section class="interest-group"><div class="section-head"><div><span class="eyebrow">Entrepreneurship &amp; creativity</span><h2>What catches my attention</h2></div></div><div class="card-grid"><article class="info-card"><h3>Fashion &amp; resale</h3><p>I sell on Depop and am interested in the move from reselling clothing to developing original designs. Fashion gives me a personal connection to questions about pricing, presentation, and customer demand.</p></article><article class="info-card"><h3>Design &amp; branding</h3><p>I enjoy developing visual ideas for clothing graphics and branded designs. For a Master Pizza employee T-shirt design, I experimented with illustration, typography, and messaging. My creative skills include Canva, video editing, and content production.</p></article><article class="info-card"><h3>Consumer psychology</h3><p>I’m curious about why people choose one product, message, or experience over another, and how psychology helps explain those decisions.</p></article></div></section>
<section class="interest-group"><div class="section-head"><div><span class="eyebrow">Outside work &amp; school</span><h2>Gaming</h2></div></div><div class="gaming-note"><p>I enjoy Overwatch and strategy games such as Hearts of Iron IV. They’re part of how I spend my time outside classes and work.</p><span>Overwatch · Hearts of Iron IV</span></div></section>
<section class="connect-banner"><div><span class="eyebrow">Shared interests</span><h2>Let’s start a conversation</h2><p>I’m happy to connect about finance, creative projects, or opportunities to learn from a different perspective.</p></div><a class="button" href="contact.html">Contact me ↗</a></section></div>'''),

"contact.html": page("Contact", "Contact Caua Kevyn Martins Brasil about finance internships and professional opportunities.", "contact.html", f'''
  <div class="wrap"><header class="page-intro compact"><span class="eyebrow">Contact / New Jersey</span><h1>Let’s connect</h1>
    <p class="lead">Email me about finance internships, project ideas, or professional opportunities, or connect with me on LinkedIn.</p></header>
    <section class="contact-panel"><div><span class="eyebrow">Start here</span><h2>Have something in mind?</h2><p class="body-copy">Tell me about the role or project, your organization, and the timing. I’m interested in opportunities to contribute and keep building my finance experience.</p>
      <a class="button" href="mailto:{EMAIL}?subject=Portfolio%20inquiry">Email me <span aria-hidden="true">↗</span></a>
      <div class="contact-note"><span class="eyebrow">Start with a topic</span><div class="contact-topics"><a href="mailto:{EMAIL}?subject=Finance%20internship%20opportunity">Internship opportunity ↗</a><a href="mailto:{EMAIL}?subject=Project%20discussion">Project discussion ↗</a><a href="mailto:{EMAIL}?subject=Professional%20connection">Professional connection ↗</a></div></div></div>
      <div class="contact-methods"><a class="contact-method" href="mailto:{EMAIL}"><span class="eyebrow">01 / Email</span><strong>{EMAIL}</strong><small>Start a conversation <span aria-hidden="true">↗</span></small></a>
        <a class="contact-method" href="{LINKEDIN}" target="_blank" rel="noopener noreferrer"><span class="eyebrow">02 / LinkedIn</span><strong>Connect professionally</strong><small>View my profile <span aria-hidden="true">↗</span></small></a>
        <a class="contact-method" href="resume.html"><span class="eyebrow">03 / Background</span><strong>See my resume</strong><small>Education and experience <span aria-hidden="true">↗</span></small></a></div>
    </section><section class="contact-next"><div><span class="eyebrow">Before you go</span><h2>Explore the work behind the resume</h2><p>Explore how I contributed to a consulting proposal, analyzed operating costs, and explained business financing options.</p></div><a class="text-link" href="projects.html">Browse projects <span aria-hidden="true">↗</span></a></section>
  </div>'''),

"project-bergecco.html": page("Bergecco-Parc Consulting", "A winning team tourism proposal for the Bergen County Historical Society, presented December 7, 2023.", "projects.html", '''
<div class="wrap project-detail"><header class="page-intro"><a class="text-link back-link" href="projects.html">← All projects</a><span class="eyebrow">Bergecco-Parc Consulting · Academic team project</span><h1>Bergecco-Parc Consulting</h1><p class="lead">A winning academic team proposal for tourism growth, event budgeting, and museum fundraising at the Bergen County Historical Society.</p><div class="button-row" style="margin-top:24px"><a class="button" href="https://www.youtube.com/watch?v=j1y3mVapkkw" target="_blank" rel="noopener noreferrer">Watch our presentation ↗</a><a class="button secondary" href="https://visitingamuseum.com/2024/01/09/bergecco-parc-consulting-inc-presents-tourism-at-the-bergen-county-historical-society-december-7th-2023/" target="_blank" rel="noopener noreferrer">Read the project coverage ↗</a></div></header>
<div class="card-grid" style="margin-bottom:14px"><article class="info-card"><span class="eyebrow">Recognition</span><h3>Winning Team Two</h3><p>The instructor’s published recap names Team Two as the competition winner.</p></article><article class="info-card"><span class="eyebrow">The brief</span><h3>2 seasonal events</h3><p>Historically grounded Halloween and Spring/Easter programming.</p></article><article class="info-card"><span class="eyebrow">Proposed fundraising</span><h3>$25,000 target</h3><p>A planning goal for the new museum, not an amount reported as raised.</p></article></div>
<div class="case-layout bergecco-case"><div>
<section class="my-contribution"><span class="eyebrow">My contribution · Team Two</span><h2>My part in the team</h2><p class="contribution-lead">I analyzed revenue streams, identified marketing channels and messages, and helped develop event concepts for the Bergen County Historical Society. Working with Team Two, I contributed to a plan to attract visitors and generate revenue for the historic site.</p><div class="contribution-grid"><article><span class="contribution-number" aria-hidden="true">01</span><h3>Revenue analysis</h3><p>I analyzed revenue streams as part of the team’s attendance and revenue growth proposal. That work connects directly to the financial side of the case: how visitor demand and revenue opportunities support a fundraising objective.</p><p class="work-example"><strong>In our team’s proposal:</strong> tiered admission prices and raffle sales formed the revenue assumptions for the museum fundraiser.</p></article><article><span class="contribution-number" aria-hidden="true">02</span><h3>Marketing channels &amp; messaging</h3><p>I identified marketing channels and messages to support the team’s attendance growth proposal. This connected the plan’s commercial objective to how the historical society could reach prospective visitors and communicate the appeal of its events.</p><p class="work-example"><strong>In our team’s proposal:</strong> brochures, flyers, QR codes, social media, and first-visit offers supported visitor outreach.</p></article><article><span class="contribution-number" aria-hidden="true">03</span><h3>Event development</h3><p>I helped develop customized event concepts to attract visitors to the center. Our shared plan connected tourism promotion with new reasons to visit the historical property.</p><p class="work-example"><strong>In our team’s proposal:</strong> Halloween and spring programming, a museum fundraiser, and an additional Revolutionary Dance concept.</p></article></div><div class="contribution-outcome"><strong>Presentations &amp; project coordination</strong><p>I communicated marketing recommendations and financial insights during team presentations and helped coordinate tasks to meet tight project deadlines.</p></div><div class="contribution-outcome"><strong>Member of the winning Team Two</strong><p>Our combined proposal won the class competition. The instructor specifically highlighted the team’s extra event as one reason for the result.</p></div><p class="contribution-credit">The examples above show how my contribution fit into our shared Team Two proposal. <a href="https://mywalkinmanhattan.com/2024/01/09/day-two-hundred-and-ninety-bergecco-parc-consulting-inc-presents-tourism-at-the-bergen-county-historical-society-december-7th-2023/" target="_blank" rel="noopener noreferrer">Read the instructor’s detailed recap ↗</a></p></section>
<section><h2>The challenge</h2><p>How could a local historical site attract more visitors while keeping its programming connected to its history? In fall 2023, our Introduction to Business class at Bergen Community College developed tourism proposals under the simulated consulting company Bergecco-Parc Consulting Inc. The assignment focused on the Bergen County Historical Society at New Bridge Landing in River Edge, New Jersey. The brief challenged teams to combine event concepts, cost planning, advertising, and fundraising in a presentation.</p></section>

<section class="event-concepts"><h2>Our event concepts</h2><p>Team Two proposed four events and outlined visitor activities, promotion, and estimated costs in the final presentation.</p><ul><li><strong>Haunted Halloween:</strong> a haunted maze, historical buildings staged as haunted houses, a costume contest, food trucks, and family activities. The visitor plan included parking signs, a brochure with an event map, and membership tables.</li><li><strong>The Easter Spectacular:</strong> a golden-egg hunt with a membership prize, a petting zoo, puppet shows, inflatable attractions, and a brunch buffet.</li><li><strong>Museum fundraiser:</strong> a family event combining food trucks, carnival games, horse rides, and a raffle, with different ticket tiers to support the $25,000 goal.</li><li><strong>Revolutionary Dance:</strong> an additional outdoor event concept for 100 guests, featuring period-inspired dress, catering, music, and $35 tickets.</li></ul><p>Source: Team Two’s presentation, slides 51–89. These concepts were proposals presented for the class project.</p></section>
<section class="financial-model"><h2>The fundraising model</h2><p>The team modeled a 700-attendee fundraiser using three ticket tiers and additional raffle sales. The projected revenue and expense figures below come from slides 75–77 and 86–87.</p>
<div style="overflow-x:auto"><table style="width:100%;border-collapse:collapse;font-size:13px;text-align:left"><caption style="text-align:left;font-weight:700;margin-bottom:12px">Original proposal assumptions</caption><thead><tr><th scope="col" style="padding:10px;border-bottom:2px solid #dfe4e9">Revenue source</th><th scope="col" style="padding:10px;border-bottom:2px solid #dfe4e9">Assumption</th><th scope="col" style="padding:10px;border-bottom:2px solid #dfe4e9;text-align:right">Projected total</th></tr></thead><tbody>
<tr><th scope="row" style="padding:10px;border-bottom:1px solid #dfe4e9;font-weight:400">All-inclusive tickets</th><td style="padding:10px;border-bottom:1px solid #dfe4e9">200 × $100</td><td style="padding:10px;border-bottom:1px solid #dfe4e9;text-align:right">$20,000</td></tr>
<tr><th scope="row" style="padding:10px;border-bottom:1px solid #dfe4e9;font-weight:400">Regular tickets</th><td style="padding:10px;border-bottom:1px solid #dfe4e9">400 × $30</td><td style="padding:10px;border-bottom:1px solid #dfe4e9;text-align:right">$12,000</td></tr>
<tr><th scope="row" style="padding:10px;border-bottom:1px solid #dfe4e9;font-weight:400">Children’s tickets</th><td style="padding:10px;border-bottom:1px solid #dfe4e9">100 × $10</td><td style="padding:10px;border-bottom:1px solid #dfe4e9;text-align:right">$1,000</td></tr>
<tr><th scope="row" style="padding:10px;border-bottom:1px solid #dfe4e9;font-weight:400">Additional raffle sales</th><td style="padding:10px;border-bottom:1px solid #dfe4e9">100 × $5</td><td style="padding:10px;border-bottom:1px solid #dfe4e9;text-align:right">$500</td></tr>
</tbody></table></div><p style="margin-top:20px"><strong>Projected revenue: $33,500<br>Listed event costs: $8,458<br>Projected net proceeds: $25,042</strong></p><p>The listed costs cover food trucks, horses, an obstacle course, a water slide, and carnival games. Revenue depends on selling the modeled mix of tickets and raffle entries. The projection clears the $25,000 target by $42, leaving little room for lower attendance or additional expenses. These figures describe the team’s original planning scenario; they are not actual funds raised.</p></section>
<section><h2>Marketing &amp; visitor engagement</h2><p>The team proposed logo concepts, billboard advertising, brochures, QR codes, flyers, and a broader social media presence. The team also proposed sending first-visit offers to Bergen County residents. On-site membership tables and event maps connected the promotion plan to the visitor experience.</p><p>The team presented the event proposals in English and Spanish in the deck to meet the assignment’s bilingual communication requirement. Source: slides 43–49 and 52–67.</p></section>
<section><h2>Presentation &amp; recognition</h2><p>The class presented on December 7, 2023. The instructor’s article names Team Two as the competition winner. The presentation linked below covers the proposed events and financial assumptions.</p><p><a class="text-link" href="https://visitingamuseum.com/2024/01/09/bergecco-parc-consulting-inc-presents-tourism-at-the-bergen-county-historical-society-december-7th-2023/" target="_blank" rel="noopener noreferrer">Read the instructor’s recap ↗</a></p></section>
<section><h2>Financial interpretation</h2><p>The proposal shows how visitor assumptions and ticket prices connect to a fundraising goal. Its narrow projected surplus highlights how cost increases or attendance shortfalls could undermine the fundraising target. The broader work combined that financial model with event planning and bilingual marketing in a shared team presentation.</p></section>
</div><aside class="case-aside"><dl><dt>Organization studied</dt><dd>Bergen County Historical Society</dd><dt>Location</dt><dd>Historic New Bridge Landing<br>River Edge, New Jersey</dd><dt>Course</dt><dd>Introduction to Business<br>Bergen Community College</dd><dt>My role</dt><dd>Team Two member</dd><dt>Presented</dt><dd>December 7, 2023</dd><dt>Focus</dt><dd>Tourism · event planning · budgeting · bilingual promotion</dd></dl></aside></div>
<section class="highlight-section" style="padding:0 0 30px"><div class="section-head"><div><span class="eyebrow">Explore the original work</span><h2>Presentation &amp; coverage</h2></div></div><div class="involvement-grid"><article class="involvement-card"><span class="tile-icon" aria-hidden="true">▶</span><span class="eyebrow">Presentation video</span><h3>Team Two’s presentation</h3><p>Watch the group’s presentation on YouTube.</p><a class="text-link" href="https://www.youtube.com/watch?v=j1y3mVapkkw" target="_blank" rel="noopener noreferrer">Watch on YouTube ↗</a></article><article class="involvement-card"><span class="eyebrow">Published January 9, 2024</span><h3>The instructor’s project recap</h3><p>Read how the instructor described the tourism brief and recognized the winning team on Visiting a Museum.</p><a class="text-link" href="https://visitingamuseum.com/2024/01/09/bergecco-parc-consulting-inc-presents-tourism-at-the-bergen-county-historical-society-december-7th-2023/" target="_blank" rel="noopener noreferrer">Read the article ↗</a></article></div></section></div>'''),

"project-operations.html": page("Operational Analysis", "An experience note on store operations, reconciliation, and business drivers.", "projects.html", '''
  <div class="wrap"><header class="page-intro compact"><a class="text-link back-link" href="projects.html">← All projects</a><span class="eyebrow">02 / Operations · analysis</span><h1>Cash Reconciliation &amp; Operations</h1>
    <p class="lead">Cash controls, operating expense analysis, and team coordination at Master Pizza.</p></header>
    <div class="case-layout"><div>
      <section><h2>The setting</h2><p>At Master Pizza, I reconcile cash, maintain deposit records, and review operating costs. I also help coordinate shifts and train staff.</p><p class="context-note">The location handles 200+ orders a day, providing context for the daily records and shift activity.</p></section>
      <section><h2>My work</h2><p>I reconcile around $1,000–$3,000 in daily cash and deposits, verify end-of-day totals, and maintain deposit records. I analyze delivery commissions, payroll, marketing budgets, and pricing to understand their effect on margins and operating performance.</p>
        <ul><li>Verify recorded cash and deposits against end-of-day activity.</li><li>Analyze delivery commissions, payroll, pricing, and marketing spend.</li></ul></section>
      <section><h2>Financial relevance</h2><p>Cash reconciliation supports the reliability of daily records by comparing reported activity with cash and deposits. Delivery commissions and payroll affect the cost of serving orders, while pricing and marketing spend influence how revenue translates into operating performance.</p><p>Reviewing daily records and operating data helps me connect these costs to business performance and strengthens my interest in cost analysis and corporate finance.</p></section>
      <section class="case-next"><a class="text-link" href="experience.html">See professional experience →</a><a class="text-link" href="resume.html">View resume →</a></section>
    </div><aside class="case-aside"><dl><dt>Setting</dt><dd>Master Pizza · Carlstadt, NJ</dd><dt>When</dt><dd>2025 — present</dd><dt>Focus</dt><dd>Reconciliation · costs · pricing · leadership</dd><dt>Tools</dt><dd>POS systems · Excel · operating records</dd></dl></aside></div>
  </div>'''),

"project-funding.html": page("Small-Business Financing", "An experience note on client discovery and small-business working-capital options.", "projects.html", '''
  <div class="wrap"><header class="page-intro compact"><a class="text-link back-link" href="projects.html">← All projects</a><span class="eyebrow">03 / Finance · client discovery</span><h1>Small-Business Financing</h1>
    <p class="lead">Client qualification and working-capital discussions during my finance internship at High Rise Capital.</p></header>
    <div class="case-layout"><div>
      <section><h2>The context</h2><p>During my finance internship at High Rise Capital, I contacted small-business owners, qualified prospects, and identified working-capital needs. I asked about their priorities before explaining potential financing options.</p></section>
      <section><h2>My approach</h2><p>I discussed merchant cash advances, lines of credit, and business loans with owners seeking $25,000–$100,000 in financing. I clarified product structures and repayment terms and connected funding discussions to needs such as payroll and advertising.</p>
        <ul><li>Conducted 100+ daily outbound contacts to identify and qualify prospective business clients.</li><li>Identified business funding needs, explained how working capital could cover payroll or advertising, and connected financing options to those priorities.</li><li>Clarified funding structures and repayment terms in plain language.</li><li>Maintained prospect records and helped advance qualified leads through application and funding stages.</li></ul></section>
      <section><h2>Financial relevance</h2><p>Working-capital discussions connect a business’s need for cash with the amount and repayment structure of potential financing. Explaining those terms clearly was central to the client conversations I supported.</p><p>I translated product terms into clear explanations and kept conversations focused on each business’s funding needs.</p></section><section><h2>Skills developed</h2><p>Through daily outreach, I practiced listening for business needs, explaining financing terms concisely, and organizing follow-up. These habits help me connect financial information to the decisions a business faces.</p></section>
      <section class="case-next"><a class="text-link" href="experience.html">See professional experience →</a><a class="text-link" href="resume.html">View resume →</a></section>
    </div><aside class="case-aside"><dl><dt>Setting</dt><dd>High Rise Capital · Manhattan, NY</dd><dt>When</dt><dd>May — June 2026</dd><dt>Focus</dt><dd>Working capital · discovery · communication</dd><dt>Product context</dt><dd>Merchant cash advances · lines of credit · business loans</dd></dl></aside></div>
  </div>'''),
}


if __name__ == "__main__":
    for filename, markup in PAGES.items():
        (ROOT / filename).write_text(markup, encoding="utf-8")
        print(filename)
